feat(preference): #DRIV-102 create user preference for nextcloud view
OPEN-ENT-NG/nextcloud pull request #102
Opened 2023-04-06 13:14 UTC by Gregprod33

## Describe your changes
In workspace, the default view for nextcloud ("documents synchonisés") is the ICON one. Now, when the user switches in LIST view, this action sets a "viewMode" preference to store the view and then he can switch from "dossier partagés" to nextcloud and the choosen view remains the same. It also works when he gets back to the icon view. 

Update Axios mock-adapter to avoid test errors (has no default export) in dev mode.
## Checklist tests
In workspace, go to "documents synchronisés", change the view mode with the button on the right, then click on "documents partagés". If you come back to "documents synchronisés", the view you had chosen is still the same. You can try it by refreshing the browser too. 
## Issue ticket number and link
[DRIV-102](https://jira.support-ent.fr/browse/DRIV-102)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-12 14:50 UTC, Sofianebernoussi approved these changes
N'oublie pas de rajouter la montée de version de axios dans la description de la pr et la raison

2023-04-12 15:03 UTC, qpic-cgi requested changes

2023-04-12 15:03 UTC, qpic-cgi commented on src/main/resources/public/ts/shared/services/nextcloud.preferences.ts
> +                if (this.isEmpty(preference)) {
donc le jour ou tu as une clé "toto" définie dans tes préférences, on arrêtera d'initialiser  viewMode à 'icons' ?
peut-être à revoir ici

2023-04-13 14:16 UTC, qpic-cgi approved these changes

2023-04-14 07:19 UTC, Gregprod33 commented on src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
> +import {NextcloudPreference, Preference} from "../../shared/services/nextcloud.preferences";
J'ai simplifié

2023-04-14 07:59 UTC, JinDouang approved these changes

2023-04-14 08:02 UTC, merged