feat(move): #DRIV-19 move folders from WS to NC is now working
OPEN-ENT-NG/nextcloud pull request #47
Opened 2022-06-22 15:06 UTC by aymericdevriesere

## Describe your changes
Following #28 We are now able to drop folders from workspace to nextcloud.
We added the corresponding changes to the API and added the copy API too.
## Checklist tests

- [ ] Drop one folder
- [ ] Drop one file
- [ ] Drop multiples folders
- [ ] Drop multiples files
- [ ] Drop multiples files and folders
- [ ] Drop multiples files and folders with spaces and special characters in their names

## Issue ticket number and link
[ DRIV - 19 ]
https://entsupport.gdapublic.fr/projects/DRIV/issues/DRIV-19
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-06-23 09:34 UTC, BastienBenard commented on src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java
> +                future.onComplete(moveStatus -> {
plutot faire un 
onSuccess -> results.add(moveStatus.result());
onFail -> results.add(new JsonObject().put("error", err.getMessage));

2022-06-23 09:38 UTC, BastienBenard commented on src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java
> +        getUniqueFileName(userSession, (parentPath != null ? parentPath + "/" : "") + document.getString(Field.NAME), 0)
On peut utilisé un constante URL_SEPARATOR = "/"

2022-06-23 16:02 UTC, JinDouang requested changes

2022-06-23 16:28 UTC, aymericdevriesere commented on src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java
> +                    EventBusHelper.requestJsonArray(eventBus, delete);
On ne veut pas attendre le retour, on lance l'appel pour que le fichier soit supprimer mais le résultat importe peu car on ne fera aucune action en cas d'échec.

2022-06-23 16:35 UTC, aymericdevriesere commented on src/main/java/fr/openent/nextcloud/helper/EventBusHelper.java
> -    public static Future<JsonObject> createFolder(EventBus eb, JsonObject action) {
J'ai supprimé toutes les fonctions de l'eventBus car elles ne servaient plus

2022-06-23 16:35 UTC, aymericdevriesere commented on src/main/java/fr/openent/nextcloud/helper/EventBusHelper.java
> -    public static Future<JsonArray> deleteDocument(EventBus eb, String id, String userId) {
J'ai supprimé toutes les fonctions de l'eventBus car elles ne servaient plus

2022-06-27 10:10 UTC, JinDouang approved these changes

2022-06-27 12:42 UTC, merged