fix(download): #DRIV-64 download folder
OPEN-ENT-NG/nextcloud pull request #70
Opened 2022-11-16 09:31 UTC by Matiyeu

## Describe your changes

Can now download a zip file from folder

## Checklist tests

- [x] Download folders / sub-folders
- [x] Download files

## Issue ticket number and link

[ DRIV-64 ](https://jira.support-ent.fr/browse/DRIV-64)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-11-16 10:31 UTC, aymericdevriesere commented on src/main/java/fr/openent/nextcloud/controller/DocumentsController.java
> +                            if (contentType == null) {
Aucun autre moyen de savoir que c'est un folder ?

2022-11-16 11:27 UTC, sjollois requested changes

2022-11-16 11:27 UTC, sjollois commented on src/main/java/fr/openent/nextcloud/controller/DocumentsController.java
> +                            if (contentType == null) {
Avec l'absence d'extension en plus par exemple ? ou alors renvoyer depuis le front l'info que c'est un dossier

2022-11-16 11:27 UTC, sjollois commented on src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java
> +                .send(responseAsync -> proceedGetFile(responseAsync, promise));
proceedGetFile à renommer comme il fait les dossiers maintenant. Pourquoi pas proceedGetDocument

2022-11-16 13:33 UTC, qpic-cgi approved these changes

2022-11-16 15:10 UTC, Matiyeu commented on src/main/java/fr/openent/nextcloud/controller/DocumentsController.java
> +                            if (contentType == null) {
J'ai ajouté un param isFolder

2022-11-16 16:45 UTC, qpic-cgi approved these changes

2022-11-17 08:50 UTC, sjollois requested changes

2022-11-17 11:19 UTC, JinDouang commented on src/main/java/fr/openent/nextcloud/controller/DocumentsController.java
> +        boolean isFolder = Boolean.parseBoolean(request.getParam(Field.ISFOLDER));
Il me semble qu'il peut gérer null pour false : 

_[The boolean returned represents the value true if the string argument is not null and is equal...](https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#parseBoolean(java.lang.String))_

2022-11-17 11:19 UTC, JinDouang approved these changes

2022-11-17 11:27 UTC, sjollois approved these changes

2022-11-17 11:35 UTC, Matiyeu commented on src/main/java/fr/openent/nextcloud/controller/DocumentsController.java
> +        boolean isFolder = Boolean.parseBoolean(request.getParam(Field.ISFOLDER));
Oui j'allais te répondre effectivement il le gère

2022-11-17 14:53 UTC, JinDouang approved these changes

2022-11-17 15:12 UTC, aymericdevriesere approved these changes

2022-11-17 16:05 UTC, merged