fix(drag): #DRIV-59 add drag over feedback
OPEN-ENT-NG/nextcloud pull request #74
Opened 2022-11-22 10:06 UTC by Matiyeu

## Describe your changes

Vu que l'on n'a pas accès au composant folder-tree, j'ai ajouté un event listener au survol de chaque dossier pour ajouter la classe `.droptarget`. Afin de garantir que le feedback est présent sur chaque sous-dossier la fonction `addDragOverListeners()` est appelée à chaque changement de dossier (en détruisant les anciens listeners puis en les recréant). 

## Checklist tests

## Issue ticket number and link

[DRIV-59](https://jira.support-ent.fr/browse/DRIV-59)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-11-22 11:12 UTC, aymericdevriesere approved these changes

2022-11-22 13:10 UTC, alicedraillard commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +        const els: any[] = Array.from(document.querySelectorAll(`[id^="droptarget-"]`));
donne un nom + parlant à ta constante

2022-11-22 13:10 UTC, alicedraillard commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +        const onDragLeave = (el) => (event) => {
idem pour el, mets au moins 'element'

2022-11-22 13:10 UTC, alicedraillard commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +        const onDragOver = (el) => (event) => {
idem

2022-11-22 13:24 UTC, alicedraillard approved these changes

2022-11-22 14:11 UTC, BastienBenard requested changes

2022-11-22 14:11 UTC, BastienBenard commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +        setTimeout(function(){ self.addDragOverListeners() }, 1000)
Indentation

2022-11-22 14:11 UTC, BastienBenard commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +        setTimeout(function(){ self.addDragOverListeners() }, 1000)
A revoir si possible pour ne pas utiliser de timeout, car cela peut varier selon la machine. Vu avec @Matiyeu

2022-11-22 15:14 UTC, sjollois approved these changes

2022-11-23 09:38 UTC, JinDouang requested changes

2022-11-23 09:38 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +    dragOverEventListeners: Map<HTMLElement, EventListener> = new Map<HTMLElement, EventListener>();
Possibilité de le mettre dans la fonction `addDragOverListeners` ?

2022-11-23 09:38 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +    dragLeaveEventListeners: Map<HTMLElement, EventListener>;
Faudrait gérer la destruction des listeners dans le $onDestroy

2022-11-23 09:38 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +        this.dragLeaveEventListeners.forEach((listener: EventListener, element: HTMLElement) => element.removeEventListener('dragleave', onDragLeave));
Une méthode pour que cette méthode + $onDestroy puisse en bénéficier

2022-11-23 09:38 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +        folders.forEach((element, i) => {
typage index

2022-11-23 09:38 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +    addDragOverListeners(): void {
Tu peux découper ta méthode en plusieurs étapes (tu as du injection html + listener, c'est 2 logiques différentes)

2022-11-23 09:40 UTC, JinDouang requested changes

2022-11-23 09:40 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +    dragLeaveEventListeners: Map<HTMLElement, EventListener>;
https://github.com/OPEN-ENT-NG/nextcloud/blob/dev/src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts#L97

2022-11-23 14:12 UTC, Matiyeu commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +                viewModel.removeDragEventListeners();
fonction

2022-11-23 14:12 UTC, Matiyeu commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +                viewModel.addDragEventListeners();
fonction

2022-11-23 14:12 UTC, Matiyeu commented on src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
> +            this.removeDragEventListeners()
fonction

2022-11-24 14:55 UTC, merged