feat(list): #DRIV-59 add view list
OPEN-ENT-NG/nextcloud pull request #77
Opened 2022-11-24 10:40 UTC by Matiyeu

## Describe your changes

add view list for nextcloud documents (iso workspace)

## Checklist tests

click on list view icon, you should see the documents in list with 3 columns : name, owner name and file size.

## Issue ticket number and link

[DRIV-65](https://jira.support-ent.fr/browse/DRIV-65)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-11-24 16:30 UTC, Matiyeu commented on src/main/java/fr/openent/nextcloud/model/Document.java
> +        this.lastModified = _lastModified;
Convert GMT to ISO date

2022-11-24 16:30 UTC, Matiyeu commented on src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
> +                        .sort(this.sortDocumentsByFolder);
Filter the list of documents by default by folder

2022-11-24 16:30 UTC, Matiyeu commented on src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
> +                        .sort(this.sortDocumentsByFolder);
Filter the list of documents by default by folder

2022-11-24 16:47 UTC, aymericdevriesere commented on src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
> +                if (a.size > b.size) return this.orderDesc ? 1 : -1;
peut être simplifiable et externalisable

2022-11-25 09:17 UTC, JinDouang requested changes

2022-11-25 09:17 UTC, JinDouang commented on src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/views/list.html
> +<article class="list-view no-margin-bottom height-minus210-mobile-1d" drop-files="newFile.files" on-drop="setFilesName();" ng-class="{'height-minus300 height-minus350-1d':infotipVisible,'height-minus
Fais des retours à la ligne pour avoir une meilleure lisibilité sur tes calls ng

2022-11-25 09:17 UTC, JinDouang commented on src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/views/list.html
> +    <table class="list-view sticky-header darkgrey primary-hover" ng-if="vm.isLoaded">
Commentaires à ajouter sur tes instructions/balises div html

2022-11-25 09:17 UTC, JinDouang commented on src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/workspace-nextcloud-content.html
> +    <container template="documents-content"></container>
commentaire pour expliquer le switch

2022-11-25 09:17 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
> +
Possibilité de créer une classe dédiée pour la viewList ? (peut-être aussi pour icons ?)

2022-11-25 09:17 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
> +    displaySize(document: SyncDocument): string {
C'est nécessaire ? ode n'a pas fait un dev pour répondre à ce besoin ?

2022-11-25 09:25 UTC, sjollois approved these changes

2022-11-25 09:25 UTC, sjollois commented on src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/views/icons.html
> +<article class="icons-view no-overflow no-margin-bottom ng-scope nextcloud-article" ng-if="vm.isLoaded"
oublie pas de mettre un commentaire pour dire que ça vient d'un autre template, qu'on ait pas besoin de trop vérifier

2022-11-29 10:18 UTC, aymericdevriesere approved these changes

2022-11-29 14:45 UTC, Matiyeu commented on src/main/resources/public/ts/sniplets/content/workspace-nextcloud-view-list.sniplet.ts
> +    orderByField (fieldName: string, desc?: boolean): void {
Based on : https://github.com/CGI-OPEN-ENT-NG/entcore/blob/dev/workspace/src/main/resources/public/ts/delegates/navigation.ts#L159

2022-11-29 15:48 UTC, merged