fix(onlyoffice): #DRIV-24 open doc located in root folder iw now working
OPEN-ENT-NG/nextcloud pull request #79
Opened 2022-11-25 15:22 UTC by aymericdevriesere

## Describe your changes
Fixed url when open file located in nextloud root folder
## Checklist tests
- [x] Open file located in root
- [x] Open file located under a subfolder of root
## Issue ticket number and link
[ DRIV-24 ] 
https://jira.support-ent.fr/browse/DRIV-24
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-11-25 15:25 UTC, sjollois requested changes

2022-11-25 15:25 UTC, sjollois commented on src/main/resources/public/ts/services/nextcloud.service.ts
> +        const url: string = document.path.substring(0, document.path.lastIndexOf('/'));
et si document.path n'a pas de "/" ?

2022-11-25 15:25 UTC, sjollois commented
il y a une faute sur le titre de ta PR

2022-11-25 15:26 UTC, BastienBenard approved these changes

2022-11-25 15:27 UTC, aymericdevriesere commented on src/main/resources/public/ts/services/nextcloud.service.ts
> +        const url: string = document.path.substring(0, document.path.lastIndexOf('/'));
Il en a forcément, les documents dans le folder root sont "/[nom du doc]"

2022-11-25 15:28 UTC, alicedraillard commented on src/main/resources/public/ts/services/nextcloud.service.ts
>  export const nextcloudService: INextcloudService = {
is* now working (nom du commit/de la PR)

2022-11-25 15:28 UTC, sjollois commented on src/main/resources/public/ts/services/nextcloud.service.ts
> +        const url: string = document.path.substring(0, document.path.lastIndexOf('/'));
une petite vérif ne coute rien pour gérer les erreurs et cas particuliers

2022-11-25 15:29 UTC, alicedraillard approved these changes

2022-11-25 15:45 UTC, BastienBenard reviewed
C'est possible de faire un test sur cette fonction ?

2022-11-28 10:24 UTC, sjollois requested changes

2022-11-28 10:24 UTC, sjollois commented on src/main/resources/public/ts/services/nextcloud.service.ts
> +        const url: string = document.path.includes("/") ? document.path.substring(0, document.path.lastIndexOf('/')) : "";             ;
; en trop

2022-11-28 11:14 UTC, sjollois approved these changes

2022-11-28 12:11 UTC, merged